/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import type { HttpResponseResolver } from 'msw'
import { http } from 'msw'

export function createPetsResponse201(data?: CreatePetsMutationResponse) {
  return new Response(JSON.stringify(data), {
    status: 201,
  })
}

export function createPets(data?: string | number | boolean | null | object | ((info: Parameters<HttpResponseResolver>[0]) => Response | Promise<Response>)) {
  return http.post('/pets', function handler(info) {
    if (typeof data === 'function') {
      return data(info)
    }

    return new Response(JSON.stringify(data), {
      status: 201,
    })
  })
}
