/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import type { HttpResponseResolver } from 'msw'
import { http } from 'msw'

export function deletePetsPetid(
  data?: string | number | boolean | null | object | ((info: Parameters<HttpResponseResolver>[0]) => Response | Promise<Response>),
) {
  return http.delete('/pets/:petId', function handler(info) {
    if (typeof data === 'function') {
      return data(info)
    }

    return new Response(JSON.stringify(data), {
      status: 200,
    })
  })
}
