/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { http } from 'msw'

export function listPetsResponse200(data: ListPetsQueryResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
    },
  })
}

export function listPetsResponse400(data?: ListPets400) {
  return new Response(JSON.stringify(data), {
    status: 400,
  })
}

export function listPets(
  data?: ListPetsQueryResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0] & { query: ListPetsQueryParams }) => Response | Promise<Response>),
) {
  return http.get('/pets', function handler(info) {
    if (typeof data === 'function') {
      const url = new URL(info.request.url)

      const query: Record<keyof ListPetsQueryParams, string | string[] | null> = {
        limit: url.searchParams.get('limit'),
        ids: url.searchParams.getAll('ids'),
      }

      return data({ ...info, query })
    }

    return new Response(JSON.stringify(data), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    })
  })
}
