/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import type { HttpResponseResolver } from 'msw'
import { http } from 'msw'

export function showPetByIdResponse200(data: ShowPetByIdQueryResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
    },
  })
}

export function showPetById(data?: ShowPetByIdQueryResponse | ((info: Parameters<HttpResponseResolver>[0]) => Response | Promise<Response>)) {
  return http.get('/pets/:petId', function handler(info) {
    if (typeof data === 'function') {
      return data(info)
    }

    return new Response(JSON.stringify(data), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    })
  })
}
